# Generated by Django 5.2.7 on 2025-10-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
           migrations.RemoveField(
               model_name='user',
               name='username',
           ),
           migrations.RemoveField(
               model_name='user',
               name='first_name',
           ),
           migrations.RemoveField(
               model_name='user',
               name='last_name',
           ),
       ]
