"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

This file has been adjusted to support production-friendly configuration:
- Read sensitive/config values from environment using python-decouple.
- WhiteNoise enabled for static file serving.
- CORS origins read from env.
- Security settings (SSL redirect, secure cookies, proxy header).
- STATIC_ROOT and STATICFILES_STORAGE configured for collectstatic.
- STATICFILES_DIRS is computed dynamically at import time to include only existing paths.
- Debug toolbar removed automatically in production (DEBUG=False).
"""

from pathlib import Path
# python-decouple may not be available to static analyzers or in minimal analysis environments.
# Use a guarded import and lightweight fallbacks so static analysis tools don't raise unresolved-import errors.
try:
    from decouple import config, Csv  # type: ignore
except Exception:
    # Minimal fallback implementations used only when python-decouple is not present.
    # These are intentionally simple and aim to make settings importable for linters/static analyzers.
    def config(key, default=None, cast=None):
        """
        Minimal stand-in for decouple.config:
        - Returns the provided default when the package isn't installed.
        - If a cast callable is provided and default is not None, attempt cast, otherwise return default.
        """
        val = default
        if callable(cast) and val is not None:
            try:
                return cast(val)
            except Exception:
                return default
        return val

    class Csv(list):
        """Very small compatibility wrapper so code that calls Csv(...) can iterate over it."""
        def __new__(cls, value=None):
            if value is None:
                return []
            if isinstance(value, list):
                return value
            return [v.strip() for v in str(value).split(',')]

from datetime import timedelta
import warnings

# cloudinary may not be available in all analysis environments; import guarded so static analyzers do not complain.
try:
    import cloudinary  # type: ignore
except Exception:
    cloudinary = None  # type: ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------
# Basic / Security-sensitive settings (read from environment)
# --------------------------------------------------------------------

# SECRET_KEY must be provided via env (or .env in development)
SECRET_KEY = config('SECRET_KEY', default='unsafe-secret-for-dev-only')

# DEBUG should be False in production
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS: specify as comma-separated list in env, e.g. "example.com,api.example.com"
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

AUTH_USER_MODEL = 'accounts.User'


# --------------------------------------------------------------------
# Application definition
# --------------------------------------------------------------------

INSTALLED_APPS = [
    # Cloudinary storage
    'cloudinary_storage',
    'cloudinary',

    # Django contrib
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'debug_toolbar',  # will be removed automatically when DEBUG=False

    # Local apps
    'accounts',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise for serving static files (should be right after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # removed automatically in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add template dirs here if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# --------------------------------------------------------------------
# Database
# Keep using the explicit DB_* variables already in the project.
# You can switch to a DATABASE_URL approach if preferred.
# --------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='postgres'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}


# --------------------------------------------------------------------
# Password validation
# --------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --------------------------------------------------------------------
# Internationalization
# --------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# Production-ready static handling using WhiteNoise
# --------------------------------------------------------------------

# URL to use when referring to static files (where they will be served from)
STATIC_URL = 'static/'

# Directory where `collectstatic` will collect static files for production
# Store collected static files outside OneDrive to avoid path length / permission issues on Windows.
# Uses the user's home directory by default (e.g. C:\Users\<user>\inventory_static).
STATIC_ROOT = Path.home() / 'inventory_static'

# WhiteNoise middleware is already configured in the MIDDLEWARE list above.

# Use WhiteNoise for serving compressed static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Static files directories
# Temporarily empty to avoid OneDrive path issues - copy frontend assets manually to staticfiles
STATICFILES_DIRS = []


# --------------------------------------------------------------------
# Cloudinary (media) configuration
# --------------------------------------------------------------------

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

# Configure cloudinary only if the module is available at runtime. This keeps static analysis
# environments from failing while preserving runtime behavior when cloudinary is installed.
if cloudinary is not None:
    cloudinary.config(
        cloud_name=config('CLOUDINARY_CLOUD_NAME', default=''),
        api_key=config('CLOUDINARY_API_KEY', default=''),
        api_secret=config('CLOUDINARY_API_SECRET', default=''),
        secure=True
    )
else:
    # cloudinary not available in this environment (e.g., static analysis); skip config.
    pass

# Use Cloudinary for media storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# --------------------------------------------------------------------
# Default primary key field type
# --------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------------------------------------------------------
# Trash / cleanup settings (project-specific)
# --------------------------------------------------------------------

TRASH_TTL_DAYS = config('TRASH_TTL_DAYS', default=2, cast=int)
ENABLE_CLEAN_TRASH_ADMIN_ENDPOINT = config('ENABLE_CLEAN_TRASH_ADMIN_ENDPOINT', default=False, cast=bool)
CLEAN_TRASH_ADMIN_SECRET = config('CLEAN_TRASH_ADMIN_SECRET', default='', cast=str)


# --------------------------------------------------------------------
# Django Debug Toolbar
# Remove debug toolbar in production for security and performance.
# --------------------------------------------------------------------
if not DEBUG:
    # Remove debug toolbar from INSTALLED_APPS and its middleware when DEBUG is False
    try:
        INSTALLED_APPS.remove('debug_toolbar')
    except ValueError:
        pass
    try:
        MIDDLEWARE.remove('debug_toolbar.middleware.DebugToolbarMiddleware')
    except ValueError:
        pass

# INTERNAL_IPS is only relevant for debug toolbar in local dev
INTERNAL_IPS = [
    '127.0.0.1',
]


# --------------------------------------------------------------------
# CORS settings
# Read allowed origins from environment variable CORS_ORIGINS (CSV)
# Example: CORS_ORIGINS="https://app.example.com,http://localhost:3000"
# --------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = config(
    'CORS_ORIGINS',
    default='http://localhost:5173,http://localhost:3000',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True


# --------------------------------------------------------------------
# REST Framework configuration
# --------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# --------------------------------------------------------------------
# Simple JWT configuration
# ACCESS_TOKEN_LIFETIME is shorter in production
# --------------------------------------------------------------------

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24) if DEBUG else timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650) if DEBUG else timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# --------------------------------------------------------------------
# Production security settings (HTTPS / cookies / proxy)
# These are read from env so you can adjust per-deployment.
# --------------------------------------------------------------------

# Redirect HTTP to HTTPS in production (enable via env)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)

# If your host (Render, Heroku, etc.) proxies HTTPS traffic, this tells Django to trust the X-Forwarded-Proto header.
# Keep this tuple as-is; some platforms set X-Forwarded-Proto to 'https' when requests are TLS-terminated upstream.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Use secure cookies to prevent session/csrf cookies from being sent over HTTP
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)


# --------------------------------------------------------------------
# Additional notes
# - Ensure you add .env to .gitignore and create .env.example that documents the expected variables.
# - Before deploying: run `python manage.py collectstatic --noinput` and verify staticfiles are collected.
# - If you encounter a ManifestStaticFilesError from WhiteNoise, check for broken static references.
# --------------------------------------------------------------------
