# Generated by Django 5.2.7 on 2025-10-29 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la plantilla (ej: Ferretería, Ropa, Restaurante)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de qué tipo de negocio es esta plantilla')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Estructura de campos personalizados que necesita este tipo de negocio')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, los usuarios pueden usarla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó esta plantilla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Negocio',
                'verbose_name_plural': 'Plantillas de Negocio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del inventario (ej: Bodega Principal, Tienda Centro)', max_length=200)),
                ('custom_template_fields', models.JSONField(blank=True, default=dict, help_text='Personalización adicional de los campos de la plantilla (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Usuario dueño de este inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Plantilla de negocio que usa este inventario', on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.businesstemplate')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('sku', models.CharField(help_text='Código único del producto (Stock Keeping Unit)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto')),
                ('quantity', models.IntegerField(default=0, help_text='Cantidad disponible en stock')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10)),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Cantidad mínima antes de alertar stock bajo')),
                ('category', models.CharField(blank=True, help_text='Categoría del producto (ej: Herramientas, Pinturas)', max_length=100)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Datos personalizados según la plantilla del inventario (ej: marca, talla, color)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(help_text='Inventario al que pertenece este producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'unique_together': {('inventory', 'sku')},
            },
        ),
    ]
