# Generated by Django 5.2.7 on 2025-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si es False, el producto está eliminado (soft delete)'),
        ),
    ]
