# Generated by Django 5.2.7 on 2025-11-02 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto almacenada en Cloudinary', max_length=255, null=True, verbose_name='image'),
        ),
    ]
