# Generated by Django 5.2.7 on 2025-11-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], help_text='Tipo de movimiento realizado', max_length=10)),
                ('quantity', models.IntegerField(help_text='Cantidad del movimiento (positivo para entradas, negativo para salidas)')),
                ('quantity_before', models.IntegerField(help_text='Cantidad antes del movimiento')),
                ('quantity_after', models.IntegerField(help_text='Cantidad después del movimiento')),
                ('reason', models.TextField(blank=True, help_text='Motivo o descripción del movimiento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento')),
                ('performed_by', models.ForeignKey(help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Producto al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='inventory_m_timesta_0865bb_idx'), models.Index(fields=['product', '-timestamp'], name='inventory_m_product_682418_idx')],
            },
        ),
    ]
