# Generated by Django 5.2.7 on 2025-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_sent',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió una alerta de stock bajo para este producto'),
        ),
    ]
