# Generated by Django 5.2.7 on 2025-11-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_alert_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla de negocio que usa este inventario (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.businesstemplate'),
        ),
    ]
