# Generated by Django 5.2.7 on 2025-11-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the product was soft-deleted (kept in trash for configurable period)', null=True),
        ),
    ]
